In [25]:
import string 

In [26]:
import re

In [28]:
import numpy as np

In [29]:
import  pandas as pd

In [30]:
import seaborn as sns

In [31]:
import matplotlib.pyplot as plt

In [32]:
from sklearn import feature_extraction

In [33]:
from sklearn import linear_model

In [34]:
from sklearn import pipeline



In [35]:
from sklearn.model_selection import train_test_split

In [36]:
from sklearn import metrics


In [39]:
eng_df = pd.read_csv("english.txt","utf-8",header= None,names =["English"])

c:\users\manishwad\anaconda3\envs\amazonpricetracker\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [40]:
eng_df.head()

English
0    Approval of the Minutes of the previous sitting
1  The Minutes of yesterday 's sitting have been ...
2                           Are there any comments ?
3  Mr President , on Monday I made a point of ord...
4  A British Labour Member of this House , Mr Mil...

In [41]:
Fr_df = pd.read_csv("French.txt","utf-8",header= None,names =["French"])

c:\users\manishwad\anaconda3\envs\amazonpricetracker\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [43]:
Fr_df.head()

French
0  Approbation du procès - verbal de la séance ...
1  Le procès - verbal de la séance d ' hier a Ã...
2                  Y a - t - il des observations - ?
3  Monsieur le Président , lundi , j ' ai soulev...
4  Un député travailliste de cette Assemblée ,...

In [44]:
It_df = pd.read_csv("Italian.txt","utf-8",header= None,names =["Italian"])

c:\users\manishwad\anaconda3\envs\amazonpricetracker\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [45]:
It_df.head()

Italian
0  Approvazione del processo verbale della seduta...
1  Il processo verbale della seduta di ieri è st...
2                             Vi sono osservazioni ?
3  Signor Presidente , lunedì ho fatto un richia...
4  L ' onorevole Miller , un eurodeputato laburis...

In [47]:
for char in string.punctuation:
    print(char,end = " ")
translate_table = dict((ord(char),None) for char in string.punctuation)

! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ 

In [49]:
data_eng= []
lang_eng = []
for i,line in eng_df.iterrows():
    line = line['English']
    if len(line)!=0:
        line = line.lower()
        line = re.sub(r"\d+","",line)
        line = line.translate(translate_table)
        data_eng.append(line)
        lang_eng.append("English")
    

In [51]:
data_fr =  []
lang_fr = []
for i,line in Fr_df.iterrows():
    line = line['French']
    if len(line)!=0:
        line = line.lower()
        line = re.sub(r"\d+","",line)
        line = line.translate(translate_table)
        data_fr.append(line)
        lang_fr.append("French")

In [52]:
data_it =  []
lang_it=[]
for i,line in It_df.iterrows():
    line = line['Italian']
    if len(line)!=0:
        line = line.lower()
        line = re.sub(r"\d+","",line)
        line = line.translate(translate_table)
        data_it.append(line)
        lang_it.append("Italian")

In [53]:
df = pd.DataFrame({"Text":data_eng+data_fr+data_it,"Language":lang_eng+lang_fr+lang_it})

In [54]:
df.head()

Text Language
0    approval of the minutes of the previous sitting  English
1  the minutes of yesterday s sitting have been d...  English
2                            are there any comments   English
3  mr president  on monday i made a point of orde...  English
4  a british labour member of this house  mr mill...  English

In [55]:
df.shape

(8186, 2)

In [56]:
X,y = df.iloc[:,0],df.iloc[:,1]


In [57]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [58]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(6548,)
(6548,)
(1638,)
(1638,)


In [61]:
vectorizer = feature_extraction.text.TfidfVectorizer(ngram_range = (1,3),analyzer = "char")

In [62]:
pipe_lr = pipeline.Pipeline([("vectorizer",vectorizer),("clf",linear_model.LogisticRegression())])

In [63]:
pipe_lr.fit(X_train,y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', ngram_range=(1, 3))),
                ('clf', LogisticRegression())])

In [64]:
y_pred = pipe_lr.predict(X_test)

In [66]:
acc = (metrics.accuracy_score(y_test,y_pred))*100

In [67]:
print(acc)

99.38949938949939


In [68]:
matrix = metrics.confusion_matrix(y_test,y_pred)

In [69]:
print(matrix)

[[571   3   1]
 [  4 515   0]
 [  2   0 542]]
